language: node_js
install:
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
cache:
  directories:
    - node_modules
services:
  - mysql
script:
  - npm run migrate